name: flutter_application_tmdb_proyecto
description: "EcoRoute - Tu ruta hacia un futuro sostenible"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:

  shared_preferences: ^2.0.15

  flutter:
    sdk: flutter
  
  http: ^1.2.0
  
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  flutter_secure_storage: ^9.2.2
  
  intl: ^0.19.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Descomenta si añades imágenes o iconos personalizados:
  # assets:
  #   - assets/images/
  #   - assets/icons/
